---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoware-vehicle-deployment
  namespace: default
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: autoware-vehicle
  template:
    metadata:
      labels:
        app: autoware-vehicle
    spec:
      containers:
        - name: autoware-vehicle
          image: autoware-vehicle-time
          command: ["/bin/sh","-c"]
          args: ["/autoware/run_vehicle.sh>/log/log_vehicle.txt"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: my-volume
              mountPath: /log
      volumes:
        - name: my-volume
          hostPath:
            path: /home/tumi6/autoware_log 

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoware-map-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoware-map
  template:
    metadata:
      labels:
        app: autoware-map
    spec:
      containers:
        - name: autoware-map
          image: autoware-map-time
          command: ["/bin/sh","-c"] 
          args: ["/autoware/run_map.sh>/log/log_map.txt"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: my-volume
              mountPath: /log
      volumes:
        - name: my-volume
          hostPath:
            path: /home/tumi6/autoware_log

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoware-system-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoware-system
  template:
    metadata:
      labels:
        app: autoware-system
    spec:
      containers:
        - name: autoware-system
          image: autoware-system-time
          command: ["/bin/sh","-c"]
          args: ["/autoware/run_system.sh>/log/log_system.txt"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: my-volume
              mountPath: /log
      volumes:
        - name: my-volume
          hostPath:
            path: /home/tumi6/autoware_log

---       
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoware-sensing-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoware-sensing
  template:
    metadata:
      labels:
        app: autoware-sensing
    spec:
      containers:
        - name: autoware-sensing
          image: autoware-sensing-time
          command: ["/bin/sh","-c"]
          args: ["/autoware/run_sensing.sh>/log/log_sensing.txt "]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: my-volume
              mountPath: /log
      volumes:
        - name: my-volume
          hostPath:
            path: /home/tumi6/autoware_log

---    
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoware-location-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoware-location
  template:
    metadata:
      labels:
        app: autoware-location
    spec:
      containers:
        - name: autoware-location
          image: autoware-location-time
          command: ["/bin/sh","-c"]
          args: ["/autoware/run_location.sh>/log/log_location.txt"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: my-volume
              mountPath: /log
      volumes:
        - name: my-volume
          hostPath:
            path: /home/tumi6/autoware_log

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoware-perception-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoware-perception
  template:
    metadata:
      labels:
        app: autoware-perception
    spec:
      containers:
        - name: autoware-perception
          image: autoware-perception-time
          command: ["/bin/sh","-c"]
          args: ["/autoware/run_perception.sh > /log/log_perception.txt"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: my-volume
              mountPath: /log
      volumes:
        - name: my-volume
          hostPath:
            path: /home/tumi6/autoware_log

---   
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoware-planning-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoware-planning
  template:
    metadata:
      labels:
        app: autoware-planning
    spec:
      containers:
        - name: autoware-planning
          image: autoware-planning-time
          command: ["/bin/sh","-c"]
          args: ["/autoware/run_planning.sh>/log/log_planning.txt"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: my-volume
              mountPath: /log
      volumes:
        - name: my-volume
          hostPath:
            path: /home/tumi6/autoware_log

---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoware-control-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoware-control
  template:
    metadata:
      labels:
        app: autoware-control
    spec:
      containers:
        - name: autoware-control
          image: autoware-control-time
          command: ["/bin/sh","-c"]
          args: ["/autoware/run_control.sh>/log/log_control.txt"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: my-volume
              mountPath: /log
      volumes:
        - name: my-volume
          hostPath:
            path: /home/tumi6/autoware_log

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoware-api-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoware-api
  template:
    metadata:
      labels: 
        app: autoware-api
    spec:
      containers:
        - name: autoware-api
          image: autoware-api-time
          command: ["/bin/sh","-c"]
          args: ["/autoware/run_api.sh>/log/log_api.txt"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: my-volume
              mountPath: /log
      volumes:
        - name: my-volume
          hostPath:
            path: /home/tumi6/autoware_log
          

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoware-rviz-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoware-rviz
  template:
    metadata:
      labels: 
        app: autoware-rviz
    spec:
      containers:
        - name: autoware-rviz
          image: autoware-rviz-time
          command: ["/bin/sh","-c"]
          args: ["/run_rviz.sh>/log/log_rviz.txt"]
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5900
          volumeMounts:
            - name: my-volume
              mountPath: /log
      volumes:
        - name: my-volume
          hostPath:
            path: /home/tumi6/autoware_log

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoware-rosbag-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoware-rosbag
  template:
    metadata:
      labels: 
        app: autoware-rosbag
    spec:
      containers:
        - name: autoware-rosbag
          image: autoware-rosbag
          command: ["/run_rosbag.sh"]
          imagePullPolicy: IfNotPresent

---
apiVersion: v1
kind: Service
metadata:
  name: port-service
spec:
  type: NodePort
  selector:
    app: autoware-rviz
  ports:
  - protocol: TCP
    nodePort: 31004
    targetPort: 5900
    port: 80
