---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoware-whole-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoware-whole
  template:
    metadata:
      labels:
        app: autoware-whole
    spec:
      containers:
        - name: autoware-whole
          image: autoware-whole-time
          command: ["/bin/sh","-c"]
          args: ["/autoware/run_autoware.sh>/log/whole_container_log_k3s.txt"]
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 5900
          volumeMounts:
            - name: my-volume
              mountPath: /log
      volumes:
        - name: my-volume
          hostPath:
            path: /home/tumi6/workspace/autoware-microservice-bench/autoware_log/whole

---
apiVersion: v1
kind: Service
metadata:
  name: port-service2
spec:
  type: NodePort
  selector:
    app: autoware-whole
  ports:
  - protocol: TCP
    nodePort: 31005
    targetPort: 5900
    port: 80

